modLoader="javafml"
loaderVersion="[52,)" # Forge 1.21.1
license="MIT"

[[mods]]
modId="chaosincube" # tady musí sedět s MOD_ID v @Mod
version="1.0.0"
displayName="Chaos v Kostce"
authors="RJbash"
description='''Je to mod vyrobený Richardem Jandíkem za účelem splnění ročníkového projektu, kdyžtak volné publikace a rejžování na ostatních lidech za účelem finančního výdělku.'''

[[dependencies.chaosincube]]
modId="forge"
mandatory=true
versionRange="[52,)"
ordering="NONE"
side="BOTH"

[[dependencies.chaosincube]]
modId="minecraft"
mandatory=true
versionRange="[1.21.1,1.22)"
ordering="NONE"
side="BOTH"